// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xytgnnefxyziimfsuela.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5dGdubmVmeHl6aWltZnN1ZWxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTAyNDksImV4cCI6MjA2ODc2NjI0OX0.luUJsyzncyEUWJlTNJLjQwdxIRZYSAscS7yckfV9nSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});